export { default as GithubIcon } from './GithubIcon'
export { default as LinkedInIcon } from './LinkedInIcon'
export { default as JSIcon } from './JSIcon'
export { default as NodeIcon } from './NodeIcon'
export { default as ReactIcon } from './ReactIcon'
export { default as InstagramIcon } from './InstagramIcon'
export { default as GmailIcon } from './GmailIcon'
